routes:
  - path: /
    controller: Home->home
    method: GET

  - path: /api/ade-ics/
    method: GET
    controller: Api->ade_ics_manual
  
  - path: /api/ade-ics/
    method: POST
    controller: Api->ade_ics